### ISSUE TITLE
Add support for fine tuning locally on a Mac with mlx

### ISSUE THREAD

**Issue by prabirshrestha** [Kiln-AI/Kiln#71]

**Comment by scosman** [comment]
I get the desire, but that's not something that really makes sense as part of Kiln. We're integrating Kiln with a range fine-tuning providers, not building low level tuning platform. If something like axolotl or Unsloth started supporting mlx, and added an API (like Ollama has) it would make a great addition. But as far as I know neither of those has robust mlx/mps support (axolotl is working on it, but not done), or APIs  (axolotl has a good CLI which might work, but no REST API).

Kiln is a nice 1-click app because we're avoiding the platform specific libraries and drivers (mlx, cuda, etc). We integrate with projects/services that run that part for inference/fine-tuning. If someone builds an "Ollama for fine-tuning" we'd be their first user 😀
